version: '3.8'
services:
  web:
    image: cv_builder
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - latex_temp:/tmp/pdf_generation:z  
      - rails_storage:/app/storage
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - BIND=0.0.0.0
    depends_on:
      - latex-service
    user: "${UID:-1000}:${GID:-1000}" 

  latex-service:
    image: latex-compiler
    volumes:
      - latex_temp:/tmp/pdf_generation:z
    command: ["sleep", "infinity"]
    user: "${UID:-1000}:${GID:-1000}"
    
volumes:
  rails_storage:
  latex_temp:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
